### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by AlexandreBonaventure** [dwqs/vue-mobx#2]
I was wondering why you want to use mobX while Vue already features reactive state and data-binding.
https://twitter.com/youyuxi/status/736939734900047874?lang=fr
From the example you display I can't see any benefits in comparison of trigerring common actions and shared state from a $root component

**Comment by dwqs** [comment]
Just want to write less verbose code.  I wouldn't like to share state from a $root component, I think it's difficult to maintain when the project more and more complex.  On the other hand,  Vue and Mobx both are great project, why not try?

**Comment by njleonzhang** [comment]
@AlexandreBonaventure I think mobx can make your code more elegant and clean without so many STRING to define `Mutations`.  `mobx` benefit `react` with reactive and elegant code. For `vue`, only elegant code from my perspective. Good job @dwqs, Thx

**Comment by dwqs** [comment]
Thx your comment and encouragement. @njleonzhang

**Comment by dwqs** [comment]
Long time no response and closed it
